apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: example-deployment
  name: example-deployment
  namespace: example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-deployment
  template:
    metadata:
      labels:
        app: example-deployment
    spec:
      containers:
      - image: 320464205386.dkr.ecr.us-west-2.amazonaws.com/template:ef0e2008efc0b4bb212ef30db0279a57b9b9158a
        name: example-deployment
        ports:
        - containerPort: 5858
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
